#!/usr/bin/env python3
"""Embed a .nnue file into a C++ source as a byte array, so the engine ships with
its network compiled in (no external file needed). Regenerate when the default net
changes:  python tools/embed_net.py <net.nnue> engine/src/eval/embedded_net.cpp
"""
import sys

src, out = sys.argv[1], sys.argv[2]
data = open(src, "rb").read()

with open(out, "w") as f:
    f.write("// GENERATED by tools/embed_net.py - do not edit.\n")
    f.write(f"// Source net: {src} ({len(data)} bytes)\n")
    f.write("#include <cstddef>\n\n")
    f.write("namespace chess { namespace nnue {\n\n")
    f.write(f"extern const unsigned char EMBEDDED_NET[{len(data)}];\n")
    f.write(f"extern const std::size_t   EMBEDDED_NET_SIZE = {len(data)};\n\n")
    f.write(f"const unsigned char EMBEDDED_NET[{len(data)}] = {{\n")
    for i in range(0, len(data), 20):
        chunk = data[i:i+20]
        f.write(" " + "".join(f"{b}," for b in chunk) + "\n")
    f.write("};\n\n} } // namespace chess::nnue\n")

print(f"wrote {out} ({len(data)} bytes embedded)")
